config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  get '/', to: 'home#index'
  root 'home#index'

  get 'search', to: 'home#search'

  resources :companies, only: %i[edit update], scope: 'admin'
  resources :companies, only: %i[show] do
    resources :job_opportunities, only: %i[show new create edit update] do
      member do
        post :enable
        post :disable
        post :apply
      end
      resources :job_applications, only: %i[show] do
        resources :responses, only: %i[] do
          member do
            post :refusal
            post :proposal
          end
        end
      end
    end
  end

  resources :employees, only: %i[show edit update]
  resources :candidates, only: %i[show edit update]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @types = %w[empresas vagas]
    @companies = Company.all
    @job_opportunities = JobOpportunity.where(status: :enable)
                                       .where('application_deadline >= ? or application_deadline is ?',
                                              Date.today, nil)
  end

  def search
    @types = %w[empresas vagas]
    @companies = Company.where('LOWER(name) LIKE LOWER(?) OR LOWER(description) LIKE LOWER(?)',
                               "%#{params[:q]}%", "%#{params[:q]}%")

    @job_opportunities = JobOpportunity.where('LOWER(title) LIKE LOWER(?) OR LOWER(description) LIKE LOWER(?)',
                                              "%#{params[:q]}%", "%#{params[:q]}%")
                                       .where(status: :enable)
                                       .where('application_deadline >= ? or application_deadline is ?',
                                              Date.today, nil)
  end
end

app/views/home/_search_form.html.erb
<div>
  <%= form_with url: search_path, method: :get do %>
    <div>
      <%= label_tag :q, 'Busca:' %>
      <%= text_field_tag :q %>
    </div>
    <div>
      <%= collection_check_boxes(:search, :types, @types, :to_s, :to_s) %>
    </div>
    <%= submit_tag 'Pesquisar' %>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Vem de Vagas</h1>

<%= render 'search_form' %>

<div class='companies'>
  <h2>Empresas</h2>
  <ul>
    <% @companies.each do |company| %>
      <li><%= link_to company.name, company %></li>
    <% end %>
  </ul>
</div>

<div class='job_opportunities'>
  <h2>Vagas</h2>
  <% @job_opportunities.each do |job_opportunity| %>
    <div>
      <%= link_to job_opportunity.title, company_job_opportunity_path(job_opportunity.company, job_opportunity) %>
      <p><%= "Vagas disponíveis: #{job_opportunity.total_job_opportunities}" %></p>
      <p>Nível: <%= human_attribute_enum(:job_opportunity,
                                        :professional_level,
                                        job_opportunity.professional_level) %>
      </p>
    </div>
  <% end %>
</div>

app/views/home/search.html.erb
<h1>Resultados</h1>

<%= render 'search_form' %>

<div class='companies'>
  <h2>Empresas</h2>
  <% if @companies.empty? %>
    <p><strong>Nenhum resultado encontrado...</strong></p>
  <% end %>

  <ul>
    <% @companies.each do |company| %>
      <li><%= link_to company.name, company %></li>
    <% end %>
  </ul>
</div>

<div class='job_opportunities'>
  <h2>Vagas</h2>
  <% if @job_opportunities.empty? %>
    <p><strong>Nenhum resultado encontrado...</strong></p>
  <% end %>

  <% @job_opportunities.each do |job_opportunity| %>
    <div>
      <%= link_to job_opportunity.title, company_job_opportunity_path(job_opportunity.company, job_opportunity) %>
      <p><%= "Vagas disponíveis: #{job_opportunity.total_job_opportunities}" %></p>
      <p>Nível: <%= human_attribute_enum(:job_opportunity,
                                        :professional_level,
                                        job_opportunity.professional_level) %>
      </p>
    </div>
  <% end %>
</div>