config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  get '/', to: 'home#index'
  root 'home#index'

  get 'search', to: 'home#search'

  resources :companies, only: %i[edit update], scope: 'admin'
  resources :companies, only: %i[show] do
    resources :job_opportunities, only: %i[show new create edit update] do
      member do
        post :enable
        post :disable
        post :apply
      end
      resources :job_applications, only: %i[show] do
        resources :responses, only: %i[] do
          member do
            post :refusal
            post :proposal
          end
        end
      end
    end
  end

  resources :employees, only: %i[show edit update]
  resources :candidates, only: %i[show edit update]
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id            :integer          not null, primary key
#  address       :string
#  cnpj          :string
#  creation_date :date
#  description   :text
#  email_domain  :string           not null
#  name          :string
#  site          :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer          not null
#
# Indexes
#
#  index_companies_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Company < ApplicationRecord
  belongs_to :admin, class_name: 'User', foreign_key: 'user_id'

  has_one_attached :cover
  has_one_attached :logo

  has_many :job_opportunities
  has_many :employee_profiles
  has_many :employees, through: :employee_profiles, source: :user

  validates :email_domain, uniqueness: { case_sensitive: false }, format: { with: /\A[a-z0-9]+\.[a-z]+(\.[a-z]+)?\z/i }
  validates :name, :cnpj, :site, presence: true, on: :update
  validates :cnpj, uniqueness: true, if: :cnpj_filled?
  validates :site, uniqueness: true, if: :site_filled?

  def employee?(user)
    employees.any? { |employee| employee == user }
  end

  private

  def cnpj_filled?
    !cnpj.nil?
  end

  def site_filled?
    !site.nil?
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :admin?, only: %i[edit update]

  def show
    @company = Company.find_by(params[:id])
    @job_opportunities = if @company&.employee?(current_user)
                           @company.job_opportunities
                         else
                           @company.job_opportunities
                                   .where(status: :enable)
                                   .where('application_deadline >= ? or application_deadline is ?',
                                          Date.today, nil)
                         end
  end

  def edit
    @company = Company.find_by(params[:id])
  end

  def update
    @company = Company.find_by(params[:id])
    if @company.update(params.require(:company)
                              .permit(:name, :description,
                                      :cnpj, :creation_date,
                                      :address, :site,
                                      :cover, :logo))
      redirect_to @company, notice: 'Empresa atualizada com sucesso!'
    else
      render 'edit'
    end
  end

  private

  def admin?
    return if current_user.admin?

    redirect_to company_path(current_user.company),
                alert: 'Apenas o administrador pode editar as informações da empresa'
  end
end

app/views/companies/edit.html.erb
<h1>Edite as informações de sua empresa</h1>

<% if @company.errors.any? %>
  <div class='alert'>
    <p>Não foi possível editar a empresa</p>
    <p>Confira os erros abaixo:</p>
    <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @company do |f| %>
  <div>
    <%= f.label :cover %>
    <%= f.file_field :cover %>
  </div>
  <div>
    <%= f.label :logo %>
    <%= f.file_field :logo %>
  </div>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :cnpj %>
    <%= f.text_field :cnpj %>
  </div>
  <div>
    <%= f.label :site %>
    <%= f.url_field :site %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :creation_date %>
    <%= f.date_field :creation_date %>
  </div>
  <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <%= f.submit %>
<% end %>

app/views/companies/show.html.erb
<% if @company.cover.attached? %>
  <%= image_tag @company.cover, alt: 'Foto de capa' %>
<% else %>
  <%= image_tag('cover_placeholder.png', alt: 'Foto de capa') %>
<% end %>
<% if @company.logo.attached? %>
  <%= image_tag @company.logo, alt: 'Logomarca' %>
<% else %>
  <%= image_tag('logo_placeholder.png', alt: 'Logomarca') %>
<% end %>

<h1><%= @company.name %></h1>
<h2><%= @company.cnpj %></h2>
<p><%= @company.description %></p>
<% if @company.creation_date %>
  <p><%= "Trabalhando desde: #{l(@company.creation_date, format: :long)}" %></p>
<% end %>
<p><%= @company.address %></p>
<p><%= @company.site %></p>

<h3>Vagas abertas</h3>

<% unless @company.job_opportunities.empty? %>
  <ul>
    <% @company.job_opportunities.each do |job_opportunity| %>
      <li>
        <%= job_opportunity.title %>: <%= t(job_opportunity.professional_level) %>
      </li>
    <% end %>
  </ul>
<% end %>


<% if @company.employee?(current_user) %>
  <%= link_to 'Criar Vaga', new_company_job_opportunity_path(@company) %>
<% end %>

<h3>Vagas</h3>
<% @job_opportunities.each do |job_opportunity| %>
  <div>
    <%= link_to job_opportunity.title, company_job_opportunity_path(job_opportunity.company, job_opportunity) %>
    <p><%= "Vagas disponíveis: #{job_opportunity.total_job_opportunities}" %></p>
    <p>Nível: <%= human_attribute_enum(:job_opportunity,
                                        :professional_level,
                                        job_opportunity.professional_level) %>
    </p>
    <% if @company.employee?(current_user) %>
      <p>
        <%= human_attribute_enum(:job_opportunity,
                                :status,
                                job_opportunity.status) %>
      </p>
    <% end %>
  </div>
<% end %>

<%= link_to 'Voltar', root_path %>