config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  get '/', to: 'home#index'
  root 'home#index'

  get 'search', to: 'home#search'

  resources :companies, only: %i[edit update], scope: 'admin'
  resources :companies, only: %i[show] do
    resources :job_opportunities, only: %i[show new create edit update] do
      member do
        post :enable
        post :disable
        post :apply
      end
      resources :job_applications, only: %i[show] do
        resources :responses, only: %i[] do
          member do
            post :refusal
            post :proposal
          end
        end
      end
    end
  end

  resources :employees, only: %i[show edit update]
  resources :candidates, only: %i[show edit update]
end

app/models/job_opportunity.rb
# == Schema Information
#
# Table name: job_opportunities
#
#  id                      :integer          not null, primary key
#  application_deadline    :date
#  description             :text
#  max_salary              :float            default(0.0), not null
#  min_salary              :float            default(0.0), not null
#  professional_level      :integer          default("junior"), not null
#  status                  :integer          default("enable"), not null
#  title                   :string           not null
#  total_job_opportunities :integer          not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  company_id              :integer          not null
#
# Indexes
#
#  index_job_opportunities_on_company_id  (company_id)
#
# Foreign Keys
#
#  company_id  (company_id => companies.id)
#
class JobOpportunity < ApplicationRecord
  after_find :updates_status

  belongs_to :company
  has_many :job_applications
  has_many :candidate_profiles, through: :job_applications, source: :candidate_profile
  has_many :candidates, through: :candidate_profiles, source: :user

  enum professional_level: { junior: 3, pleno: 6, senior: 9 }
  enum status: { enable: 3, disable: 6 }

  validates :title, presence: true
  validates :max_salary, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :min_salary, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :professional_level, presence: true
  validates :total_job_opportunities, presence: true
  validates :status, presence: true

  def job_application_for(user)
    job_applications.find_by(candidate_profile: user.candidate_profile)
  end

  private

  def updates_status
    disable! if enable? && (!application_deadline.nil? && application_deadline < Date.today)
  end
end

app/controllers/job_opportunities_controller.rb
class JobOpportunitiesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update enable disable apply]

  def show
    @job_opportunity = JobOpportunity.find(params[:id])
    @company = @job_opportunity.company
    return redirect_to root_path unless job_opportunity_valid?
  end

  def new
    company_employee?
    @company = Company.find(params[:company_id])
    @job_opportunity = JobOpportunity.new
  end

  def create
    company_employee?
    @job_opportunity = JobOpportunity.new(job_opportunity_params)
    @job_opportunity.company = current_user.company
    if @job_opportunity.save
      redirect_to @job_opportunity.company, notice: 'Vaga criada com sucesso'
    else
      @company = Company.find(params[:company_id])
      render 'new', alert: 'Não foi possível criar a vaga'
    end
  end

  def edit
    company_employee?
    @job_opportunity = JobOpportunity.find(params[:id])
  end

  def update
    company_employee?
    @job_opportunity = JobOpportunity.find(params[:id])
    if @job_opportunity.update(job_opportunity_params)
      redirect_to company_job_opportunity_path(@job_opportunity.company, @job_opportunity)
    else
      @company = Company.find(params[:company_id])
      render 'edit'
    end
  end

  def enable
    company_employee?
    @job_opportunity = JobOpportunity.find(params[:id])
    @job_opportunity.enable! if @job_opportunity.disable?
    redirect_to company_job_opportunity_path(@job_opportunity.company, @job_opportunity)
  end

  def disable
    company_employee?
    @job_opportunity = JobOpportunity.find(params[:id])
    @job_opportunity.disable! if @job_opportunity.enable?
    redirect_to company_job_opportunity_path(@job_opportunity.company, @job_opportunity)
  end

  def apply
    job_opportunity = JobOpportunity.find(params[:id])
    return redirect_to company_path(job_opportunity.company) if job_opportunity.company.employee?(current_user)

    JobApplication.create(candidate_profile: current_user.candidate_profile, job_opportunity: job_opportunity)
    redirect_to company_job_opportunity_path(job_opportunity.company, job_opportunity),
                notice: 'Sua candidatura já foi enviada, aguarde por uma resposta'
  end

  private

  def job_opportunity_params
    params.require(:job_opportunity).permit(:title, :description,
                                            :min_salary, :max_salary,
                                            :application_deadline,
                                            :total_job_opportunities, :professional_level)
  end

  def company_employee?
    company = Company.find(params[:company_id])
    return redirect_to root_path unless company.employee?(current_user)
  end

  def job_opportunity_valid?
    if !@job_opportunity&.company&.employee?(current_user) &&
       (@job_opportunity.nil? || @job_opportunity.disable?)
      return false
    end

    true
  end
end

app/views/job_opportunities/edit.html.erb
<h1>Edite sua vaga</h1>

<% if @job_opportunity.errors.any? %>
  <div class='alert'>
    <p>Não foi possível atualizar a vaga</p>
    <p>Confira os erros abaixo:</p>
    <ul>
      <% @job_opportunity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @job_opportunity,
              url: company_job_opportunity_path(@job_opportunity.company) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :min_salary %>
    <%= f.number_field :min_salary %>
  </div>
  <div>
    <%= f.label :max_salary %>
    <%= f.number_field :max_salary %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.collection_radio_buttons :professional_level, JobOpportunity.professional_levels, :first, :first %>
  </div>
  <div>
    <%= f.collection_radio_buttons :status, JobOpportunity.statuses, :first, :first %>
  </div>
  <div>
    <%= f.label :total_job_opportunities %>
    <%= f.number_field :total_job_opportunities %>
  </div>
  <div>
    <%= f.label :application_deadline %>
    <%= f.date_field :application_deadline %>
  </div>

  <%= f.submit %>
<% end %>

app/views/job_opportunities/new.html.erb
<h1>Crie uma vaga</h1>

<% if @job_opportunity.errors.any? %>
  <div class='alert'>
    <p>Não foi possível criar a vaga</p>
    <p>Confira os erros abaixo:</p>
    <ul>
      <% @job_opportunity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @job_opportunity,
              url: company_job_opportunities_path(@company) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :min_salary %>
    <%= f.number_field :min_salary %>
  </div>
  <div>
    <%= f.label :max_salary %>
    <%= f.number_field :max_salary %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.collection_radio_buttons :professional_level, JobOpportunity.professional_levels, :first, :first %>
  </div>
  <div>
    <%= f.collection_radio_buttons :status, JobOpportunity.statuses, :first, :first %>
  </div>
  <div>
    <%= f.label :total_job_opportunities %>
    <%= f.number_field :total_job_opportunities %>
  </div>
  <div>
    <%= f.label :application_deadline %>
    <%= f.date_field :application_deadline %>
  </div>

  <%= f.submit %>
<% end %>

app/views/job_opportunities/show.html.erb
<h1><%= @job_opportunity.title %></h1>

<% if @job_opportunity.enable? %>
  <%= link_to 'Inativar', disable_company_job_opportunity_path(@company, @job_opportunity), method: :post %>
<% end %>
<% if @job_opportunity.disable? %>
  <%= link_to 'Ativar', enable_company_job_opportunity_path(@company, @job_opportunity), method: :post %>
<% end %>

<%= "Salário: #{number_to_currency(@job_opportunity.min_salary)} -" +
    " #{number_to_currency(@job_opportunity.max_salary)}" %>
<%= @job_opportunity.description %>
<%= human_attribute_enum(:job_opportunity,
                          :professional_level,
                          @job_opportunity.professional_level) %>
<% unless @job_opportunity.application_deadline.nil? %>
  <%= "Vaga disponível até #{l(@job_opportunity.application_deadline, format: :long)}" %>
<% end %>

<% if @company.employee?(current_user) %>
  <%= human_attribute_enum(:job_opportunity,
                          :status,
                          @job_opportunity.status) %>
<% end %>

<%= "Número de vagas disponíveis: #{@job_opportunity.total_job_opportunities}" %>

<% unless @company.employee?(current_user) %>
  <% if current_user&.applied?(@job_opportunity) %>
    <p>Você já se candidatou a esta vaga</p>
    <%= link_to 'Detalhes da Candidatura',
                company_job_opportunity_job_application_path(@company,
                                                             @job_opportunity,
                                                             @job_opportunity.job_application_for(current_user)) %>
  <% else %>
    <%= link_to 'Candidatar-se',
                apply_company_job_opportunity_path(@company, @job_opportunity),
                method: :post %>
  <% end %>
<% end %>

<% if @company.employee?(current_user) %>
  <h2>Candidaturas</h2>
  <% @job_opportunity.candidates.each do |candidate| %>
    <%= link_to candidate.full_name,
                company_job_opportunity_job_application_path(@company,
                                                             @job_opportunity,
                                                             @job_opportunity.job_application_for(candidate)) %>
  <% end %>
<% end %>

<%= link_to 'Editar Vaga', edit_company_job_opportunity_path(@company, @job_opportunity) %>
<%= link_to @company.name, company_path(@company) %>
<%= link_to 'Voltar', company_path(@company) %>