config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  get '/', to: 'home#index'
  root 'home#index'

  get 'search', to: 'home#search'

  resources :companies, only: %i[edit update], scope: 'admin'
  resources :companies, only: %i[show] do
    resources :job_opportunities, only: %i[show new create edit update] do
      member do
        post :enable
        post :disable
        post :apply
      end
      resources :job_applications, only: %i[show] do
        resources :responses, only: %i[] do
          member do
            post :refusal
            post :proposal
          end
        end
      end
    end
  end

  resources :employees, only: %i[show edit update]
  resources :candidates, only: %i[show edit update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vem De Vagas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar.variant(resize_to_limit: [100, 100]), alt: 'Foto de Perfil' %>
        <% else %>
          <%= image_tag('avatar_placeholder.png', size: '100', alt: 'Foto de Perfil') %>
        <% end %>
        <% if current_user.as_employee? %>
          <%= link_to current_user.username, employee_path(current_user) %>
        <% else %>
          <%= link_to current_user.username, candidate_path(current_user) %>
        <% end %>

        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>

        <% if current_user.as_employee? %>
          <%= link_to 'Minha Empresa', company_path(current_user.company) %>
        <% end %>

      <% else %>
        <%= link_to 'Entrar', new_user_session_path %>
      <% end %>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>